name: ts
channels:
  - anaconda
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - rise
  - slim
  - pillow
  - matplotlib
  - numpy
  - pandas
  - jupyter
  - tskit
  - msprime
  - pip:
    - pyslim
